config/routes.rb
Merchant::Application.routes.draw do
  resources :orders

  resources :order_items

  resources :products

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :status

  has_many :order_items, dependent: :destroy
  has_many :products, :through => :order_items

  def total
  	total = order_items.inject(0) { |sum, p| sum + p.subtotal }
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  attr_accessible :product_id, :order_id, :quantity

  validates :order_id,  :presence => true
  validates :product_id, :presence => true
  
  belongs_to :order
  belongs_to :product
  
  def subtotal
	  quantity * product.price 
	  #number_to_currency(item.quantity * item.product.price)
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :price, :description, :image_url, :stock
validates_numericality_of :price
validates :stock, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0}
has_many :order_items, dependent: :destroy
has_many :orders, :through => :order_items
def price=(input)
	input.delete!("$")
	super
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def load_order
    @order = Order.find_or_initialize_by_id(session[:order_id], status: "Unsubmitted")
    if @order.new_record?
      @order.save!
      session[:order_id] = @order.id
    end
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_filter :load_order

  def create
    @order.order_items.create(quantity: 1, product_id: params[:product_id])
    redirect_to @order, :notice => "Successfully created order item."
  end

  def edit
    @order_item = OrderItem.find(params[:id])
  end

  def update
    @order_item = OrderItem.find(params[:id])
    if @order_item.update_attributes(params[:order_item])
      redirect_to @order_item, :notice  => "Successfully updated order item."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @order_item = OrderItem.destroy(params[:id])
    redirect_to order_path(@order_item.order), :notice => "Successfully destroyed order item."
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params[:order])
    if @order.save
      redirect_to @order, :notice => "Successfully created order."
    else
      render :action => 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update_attributes(params[:order])
      redirect_to @order, :notice  => "Successfully updated order."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
          redirect_to products_url, :notice => "Successfully destroyed product."
    else
          redirect_to order_items_url, :notice => "Successfully destroyed product."
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :load_order

    def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, :notice => "Successfully created product."
    else
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, :notice => "Successfully destroyed product."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	def print_price(price)
		number_to_currency price
	end

	def print_stock(stock)
		if stock > 0
			"In Stock (#{stock}) "
			

		else
			"Out of Stock"
		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodWorks- Products: <%= controller.action_name %></title>

   
 
    <%= stylesheet_link_tag 'styles' %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <p style="color: green"><%= flash[:notice] %></p>
<div class="wrapper">
    <div class="header">
      <h1>FoodWorks- Products: <%= controller.action_name %></h1>
      <p>Your Online Grocery</p>
    </div>

    <div class="sidebar">
      (sidebar)
    </div>

    <div class="main">
      <%= yield %>
    </div>

    <div class="footer">
      FoodWorks Online Grocery<br/>
      A Rails Jumpstart Project
    </div>
</div>

  </body>
</html>

app/views/order_items/_form.html.erb
<%= form_for @order_item do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </p>
  <p>
    <%= f.label :order_id %><br />
    <%= f.number_field :order_id %>
  </p>
  <p>
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/order_items/edit.html.erb
<% title "Edit Order Item" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @order_item %> |
  <%= link_to "View All", order_items_path %>
</p>

app/views/order_items/index.html.erb
<% title "Order Items" %>

<table>
  <tr>
    <th>Product</th>
    <th>Order</th>
    <th>Quantity</th>
  </tr>
  <% for order_item in @order_items %>
    <tr>
      <td><%= order_item.product_id %></td>
      <td><%= order_item.order_id %></td>
      <td><%= order_item.quantity %></td>
      <td><%= link_to "Show", order_item %></td>
      <td><%= link_to "Edit", edit_order_item_path(order_item) %></td>
      <td><%= link_to "Destroy", order_item, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Order Item", new_order_item_path %></p>

app/views/order_items/new.html.erb
<% title "New Order Item" %>

<%= render 'form' %>

<p><%= link_to "Back to List", order_items_path %></p>

app/views/order_items/show.html.erb
<% title "Order Item" %>

<p>
  <strong>Product:</strong>
  <%= @order_item.product_id %>
</p>
<p>
  <strong>Order:</strong>
  <%= @order_item.order_id %>
</p>
<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>

<p>
  <%= link_to "Edit", edit_order_item_path(@order_item) %> |
  <%= link_to "Destroy", @order_item, :confirm => 'Are you sure?', :method => :delete %> 
  <%= link_to "View All", order_items_path %>
</p>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :customer_id %><br />
    <%= f.number_field :customer_id %>
  </p>
  <p>
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/orders/edit.html.erb
<% title "Edit Order" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @order %> |
  <%= link_to "View All", orders_path %>
</p>

app/views/orders/index.html.erb
<% title "Orders" %>

<table>
  <tr>
    <th>Customer</th>
    <th>Status</th>
  </tr>
  <% for order in @orders %>
    <tr>
      <td><%= order.customer_id %></td>
      <td><%= order.status %></td>
      <td><%= link_to "Show", order %></td>
      <td><%= link_to "Edit", edit_order_path(order) %></td>
      <td><%= link_to "Destroy", order, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Order", new_order_path %></p>

app/views/orders/new.html.erb
<% title "New Order" %>

<%= render 'form' %>

<p><%= link_to "Back to List", orders_path %></p>

app/views/orders/show.html.erb
<h1>Your Order</h1>

<table>
  <tr>
    <th>Customer</th>
    <td><%= @order.customer_id %></td>
  </tr>
  <tr>
    <th>Status:</th>
    <td><%= @order.status %></td>
  </tr>
  <tr>
    <th>Items:</th>
    <td><%= @order.order_items.count %></td>
  </tr>
  <tr>
    <th>Items</th>
    <th>Title</th>
    <th>Quantity</th>
    <th>Unit Price</th>
    <th>Subtotal</th>
    <th>Order Total</th>
  </tr>
<% @order.order_items.each do |item| %>
<tr>
	<td><%= image_tag "/images/products/#{item.product.image_url}" %></td>
	<td><%= item.product.title %></td>
	<td><%= item.quantity %></td>
	<td><%= print_price(item.product.price)%></td>
	<td><%= number_to_currency(item.subtotal) %></td>
  <td><%= number_to_currency(@order.total)%></td>
  <td><%= link_to "Remove", item, :confirm => 'Are you sure?', :method => :delete, :product_id => item.product_id %></td>
</tr>

<% end %>
</table>
<p>
  <%= link_to "Empty Cart", @order, confirm: 'Are you sure?', method: :delete %>
</p>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :price, "Price(like 2.99)" %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :stock %><br />
    <%= f.text_field :stock %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/products/edit.html.erb
<% title "Edit Product" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @product %> |
  <%= link_to "View All", products_path %>
</p>

app/views/products/index.html.erb
<h1><% title "All Products" %></h1>

<table>
  <tr>

    <th>Image Url</th>
    <th>Title & Description</th>
    
    <th>Price</th>
    <th>Stock</th>
    <th>Buy</th>
    
  </tr>
  <% @products.each do |product| %>
  <tr>
    <td><%= image_tag "/images/products/#{product.image_url}" %></td>
    <td><span class="product_title"><%= product.title %></span><%= product.description %></td>
    <td><%= print_price(product.price) %></td>
    <td><%= print_stock(product.stock) %></td>
    <td><%= button_to "Add to Cart", order_items_path(product_id: product.id)%></td>
    <td><%= link_to "Show", product_path(product) %></td>
      <td><%= link_to "Edit", edit_product_path(product) %></td>
      <td><%= link_to "Destroy", product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

      
    
  
</table>

<p><%= link_to "Create a New Product", new_product_path, id: "new_product" %></p>

app/views/products/new.html.erb
<h1><% title "Create a New Product" %></h1>

<%= render 'form' %>

<p><%= link_to "Back to List", products_path %></p>

app/views/products/show.html.erb
<% title "Product" %>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Image Url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Destroy", @product, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", products_path %>
</p>